import type { BotProductRow } from "@/types/bot-control";

export const BOT_PRODUCT_ROWS: BotProductRow[] = [
  {
    id: "bot-1",
    sku: "MB-EAR-001",
    name: "Kablosuz Bluetooth Kulaklık Pro",
    marketplace: "Trendyol",
    category: "Electronics",
    productCostUsd: 28.5,
    weightDesi: 1.2,
    currentPriceTl: 1849,
    competitorPriceTl: 1720,
    floorPriceTl: 1750,
    minMarginPercent: 15,
    stock: 42,
    botEnabled: true,
  },
  {
    id: "bot-2",
    sku: "MB-SER-002",
    name: "C Vitamini Serum 30ml",
    marketplace: "Hepsiburada",
    category: "Cosmetics",
    productCostUsd: 12,
    weightDesi: 0.5,
    currentPriceTl: 1299,
    competitorPriceTl: 1180,
    floorPriceTl: 1220,
    minMarginPercent: 18,
    stock: 8,
    botEnabled: true,
  },
  {
    id: "bot-3",
    sku: "MB-HOD-003",
    name: "Premium Oversize Hoodie",
    marketplace: "Trendyol",
    category: "Apparel",
    productCostUsd: 18.75,
    weightDesi: 2,
    currentPriceTl: 2199,
    competitorPriceTl: 2100,
    floorPriceTl: 2050,
    minMarginPercent: 12,
    stock: 18,
    botEnabled: false,
  },
  {
    id: "bot-4",
    sku: "MB-LMP-004",
    name: "Akıllı LED Masa Lambası",
    marketplace: "N11",
    category: "Home & Garden",
    productCostUsd: 22,
    weightDesi: 1.8,
    currentPriceTl: 1679,
    competitorPriceTl: 1650,
    floorPriceTl: 1580,
    minMarginPercent: 15,
    stock: 31,
    botEnabled: true,
  },
];
